### ISSUE TITLE
rRNA construction and annotation

### ISSUE THREAD

**Issue by JeanneLaurentie** [nickp60/riboSeed#11]
I used riboSeed to improve assembly of genomes collection. My reference genome has 7 ribosomic operons annotated but when I annotated my own assemblies built with option "trusted contigs", I have, in the best case, only 5 or 6 operons detected by annotation tool.
Is this a classic issue ?

Thanks

**Comment by nickp60** [comment]
Hi @JeanneLaurentie, yes, the number of rDNAs that riboSeed can correct is mainly influenced by (a) how much diversity there is in the regions flanking the rDNA operon, and (b) how closely related the reference is. You may be able to improve performance by finding a closer reference genome, but for some genomes, 5 or 6 of the 7 may be the best possible case.

**Comment by nickp60** [comment]
This is still in development, this is the tool I use to find the optimal reference: https://github.com/nickp60/plentyofbugs

**Comment by JeanneLaurentie** [comment]
Thanks a lot for answer ! We have only one reference genome for this bacterium, so no choice.
