### ISSUE TITLE
Run with IonTorrent single reads

### ISSUE THREAD

**Issue by avilaHugo** [nickp60/riboSeed#13]
Dear developers,
Is there a way to pass the spades flag "--iontorrent" to your pipeline or are only illumina reads allowed ?

**Comment by nickp60** [comment]
Hi @avilaHugo ,
It should work out of the box without needing to pass that flag.  I have assembled some IonTorrent datasets and haven't had any issues in the past.  One caveat is that the default behavior is to *not* use SPAdes's built-in error correction after [their comparison with SKESA](http://cab.spbu.ru/benchmarking-tools-for-de-novo-microbial-assembly/).   The `--iontorrent` flag is just used to switch from BayesHammer to IonHammer as far as I know -- neither of which are used by riboSeed.  

If you run into any errors, let me know!

**Comment by avilaHugo** [comment]
@nickp60 thank you !!!
