### ISSUE TITLE
not an issue but critical feedback

### ISSUE THREAD

**Issue by peterthorpe5** [nickp60/riboSeed#4]
line 217  riboScan.py   :

fastas = glob.glob(str(args.contigs_dir + "*" + args.ext))

this requires the command line to be the exact path with "/" at the end.
If you used os.path.join(args.contigs_dir, "*" + args.ext)  - this might be more flexible?? And less prone to user error(?)

Just a thought!

Cheers,

Pete

**Comment by nickp60** [comment]
Totally agree!  I'll add expanduser to ensure relative paths wont be a problem either...
