### ISSUE TITLE
riboseed2? or 1?

### ISSUE THREAD

**Issue by peterthorpe5** [nickp60/riboSeed#5]
"...riboSeed.py is used to map reads to the extracted regions ...... RiboSeed2 differs from the legacy version of riboSeed as riboSeed maps to all the regions at once, which minimizes the complications associated with multiple mappings. Instead of mapping to all the regions ind...."

Is the current version on Master riboSeed2? This can cause confusion to the user. Perhaps, state the legacy version did this but the current version (2) does this.

Just a thought.

Pete

**Comment by nickp60** [comment]
Got it corrected;  it seemed like a good idea to mention it at the time, but definitely not needed now!
