### ISSUE TITLE
testing RiboSeed on Fedora 25

### ISSUE THREAD

**Issue by stevebaeyen** [nickp60/riboSeed#9]
I wanted to try out the method with ribo run command (the easy way) but this didn’t work after installation with conda on Linux Fedora 25.
Thus, I tried the scan step with: 
 
[guest@localhost ref]$ python3 /home/guest/anaconda3/bin/riboScan.py -o /home/guest/Documenten/riboscan  -b ~/anaconda3/bin/barrnap -s ~/anaconda3/bin/seqret /home/guest/Documenten/ref
2017-10-23 16:11:34 - INFO - Initializing logger
2017-10-23 16:11:34 - INFO - Usage:
/home/guest/anaconda3/bin/riboScan.py -o /home/guest/Documenten/riboscan /home/guest/Documenten/ref
 
2017-10-23 16:11:34 - INFO - Accession for /home/guest/Documenten/ref/968-1.fa: 968-1
2017-10-23 16:11:34 - INFO - running barrnap cmd: /home/guest/anaconda3/bin/barrnap -k bac /home/guest/Documenten/ref/968-1.fa --reject 0.5 --threads 2 > /home/guest/Documenten/riboscan/968-1.gff
Traceback (most recent call last):
  File "/home/guest/anaconda3/bin/riboScan.py", line 416, in <module>
    main(args)
  File "/home/guest/anaconda3/bin/riboScan.py", line 382, in main
    check=True)
  File "/usr/lib64/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/guest/anaconda3/bin/barrnap -k bac /home/guest/Documenten/ref/968-1.fa --reject 0.5 --threads 2 > /home/guest/Documenten/riboscan/968-1.gff' returned non-zero exit status 2
 
Any idea what is going wrong here ?
I checked the fasta file and header, and it seems OK (no amiguous symbols). The gff file is created but empty.

**Comment by nickp60** [comment]
Hi @stevebaeyen, Sorry to hear you're having issues!  What is the result of running the barrnap command by itself?
    
    /home/guest/anaconda3/bin/barrnap -k bac /home/guest/Documenten/ref/968-1.fa --reject 0.5 --threads 2 > /home/guest/Documenten/riboscan/968-1.gff

Without seeing the result, I would guess that it has to do with some of barrnap's Perl dependencies, which has been problematic for me before (depending on the linux distro)..

**Comment by nickp60** [comment]
I am going to close this issue, but please re-open if issues persist after sorting out barrnap.  Alternatively, try using barrnap-python (https://github.com/nickp60/barrnap-python), which is the same program ported to python to avoid the perl dependencies
